# Generated by Django 5.2 on 2025-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
