# Generated by Django 5.2 on 2025-04-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_admindata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admindata",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
