# Generated by Django 5.2 on 2025-04-11 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_admindata_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефону повинен бути у форматі: +380XXXXXXXXX",
                                regex="^\\+380\\d{9}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="main.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
