# Generated by Django 5.2 on 2025-04-11 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефону повинен бути у форматі: +380XXXXXXXXX",
                        regex="^\\+380\\d{9}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
